"""Initial migration.

Revision ID: 977f4e95dce2
Revises: 456a945560f6
Create Date: 2020-10-11 00:07:12.650593

"""

# revision identifiers, used by Alembic.
revision = '977f4e95dce2'
down_revision = '456a945560f6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrap', sa.Column('validity_grade', sa.String(length=64), nullable=False))
    op.alter_column('scrap', 'country',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('scrap', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('scrap', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('scrap', 'industry',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.alter_column('scrap', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
    op.alter_column('scrap', 'link',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('scrap', 'position',
               existing_type=sa.VARCHAR(length=128),
               nullable=False)
    op.drop_column('scrap', 'company')
    op.drop_column('scrap', 'scrap_date')
    op.drop_column('scrap', 'validity_check')
    op.drop_column('scrap', 'percentage')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scrap', sa.Column('percentage', sa.FLOAT(), nullable=True))
    op.add_column('scrap', sa.Column('validity_check', sa.VARCHAR(length=64), nullable=True))
    op.add_column('scrap', sa.Column('scrap_date', sa.DATE(), nullable=True))
    op.add_column('scrap', sa.Column('company', sa.VARCHAR(length=128), nullable=True))
    op.alter_column('scrap', 'position',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('scrap', 'link',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('scrap', 'last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('scrap', 'industry',
               existing_type=sa.VARCHAR(length=128),
               nullable=True)
    op.alter_column('scrap', 'first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('scrap', 'email',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.alter_column('scrap', 'country',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
    op.drop_column('scrap', 'validity_grade')
    # ### end Alembic commands ###
